name: cratenet_env

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pymatgen=2020.10.20
  - matplotlib=3.3.4
  - numpy=1.18.5
  - scikit-learn=0.24.2
  - tqdm=4.64.1
  - pip
  - pip:
      - tensorflow==2.3.1
      - matminer==0.6.3
      - smact==2.3.1
      - requests~=2.27.1
      - scipy~=1.5.3
